package com.eduportal.dao;

import com.eduportal.model.Enrollment;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Data Access Object for the Enrollment entity.
 * Implements full CRUD operations with Foreign Keys (StudentID, CourseID).
 */
public class EnrollmentDAO implements BaseDAO<Enrollment> {

    private static final String INSERT_SQL = "INSERT INTO Enrollment (StudentID, CourseID, ReferenceID, Description, EnrollDate, Status, Remarks) VALUES (?, ?, ?, ?, ?, ?, ?)";
    private static final String SELECT_ALL_SQL = "SELECT * FROM Enrollment";
    private static final String SELECT_BY_ID_SQL = "SELECT * FROM Enrollment WHERE EnrollmentID = ?";
    private static final String UPDATE_SQL = "UPDATE Enrollment SET StudentID=?, CourseID=?, ReferenceID=?, Description=?, EnrollDate=?, Status=?, Remarks=? WHERE EnrollmentID=?";
    private static final String DELETE_SQL = "DELETE FROM Enrollment WHERE EnrollmentID=?";

    /**
     * Helper method to convert a ResultSet row into an Enrollment object.
     */
    private Enrollment extractEnrollmentFromResultSet(ResultSet rs) throws SQLException {
        // NOTE: This assumes a constructor in Enrollment.java matching the table columns
        return new Enrollment(
            rs.getInt("EnrollmentID"),
            rs.getInt("StudentID"),
            rs.getInt("CourseID"),
            rs.getString("ReferenceID"),
            rs.getString("Description"),
            rs.getTimestamp("EnrollDate"),
            rs.getString("Status"),
            rs.getString("Remarks")
        );
    }

    @Override
    public boolean insert(Enrollment enrollment) {
        Connection conn = null;
        PreparedStatement ps = null;
        try {
            conn = DatabaseConnector.getConnection();
            
            // We use RETURN_GENERATED_KEYS to get the auto-increment ID from MySQL
            ps = conn.prepareStatement(INSERT_SQL, Statement.RETURN_GENERATED_KEYS);
            
            // Setting the parameters
            ps.setInt(1, enrollment.getStudentID());
            ps.setInt(2, enrollment.getCourseID());
            ps.setString(3, enrollment.getReferenceID());
            ps.setString(4, enrollment.getDescription());
            
            // Converting java.util.Date to java.sql.Timestamp
            ps.setTimestamp(5, new Timestamp(enrollment.getEnrollDate().getTime()));
            
            ps.setString(6, enrollment.getStatus());
            ps.setString(7, enrollment.getRemarks());
            
            // Execute the insert
            int affectedRows = ps.executeUpdate();
            
            // If the insert was successful, retrieve the new ID
            if (affectedRows > 0) {
                try (ResultSet generatedKeys = ps.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        // Update the enrollment object with the ID generated by WAMP/MySQL
                        enrollment.setEnrollmentID(generatedKeys.getInt(1));
                    }
                }
                return true;
            }
            
            return false;
        } catch (SQLException e) {
            System.err.println("Error inserting enrollment: " + e.getMessage());
            e.printStackTrace();
            return false;
        } finally {
            // Safe closing of resources
            try { if (ps != null) ps.close(); } catch (SQLException e) { /* ignore */ }
            try { if (conn != null) conn.close(); } catch (SQLException e) { /* ignore */ }
        }
    }
    @Override
    public Enrollment getById(int id) {
        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            conn = DatabaseConnector.getConnection();
            ps = conn.prepareStatement(SELECT_BY_ID_SQL);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            if (rs.next()) {
                return extractEnrollmentFromResultSet(rs);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try { if (rs != null) rs.close(); } catch (SQLException e) { /* ignore */ }
            try { if (ps != null) ps.close(); } catch (SQLException e) { /* ignore */ }
            try { if (conn != null) conn.close(); } catch (SQLException e) { /* ignore */ }
        }
        return null;
    }

    @Override
    public List<Enrollment> getAll() {
        List<Enrollment> enrollments = new ArrayList<Enrollment>();
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;
        try {
            conn = DatabaseConnector.getConnection();
            stmt = conn.createStatement();
            rs = stmt.executeQuery(SELECT_ALL_SQL);
            while (rs.next()) {
                enrollments.add(extractEnrollmentFromResultSet(rs));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try { if (rs != null) rs.close(); } catch (SQLException e) { /* ignore */ }
            try { if (stmt != null) stmt.close(); } catch (SQLException e) { /* ignore */ }
            try { if (conn != null) conn.close(); } catch (SQLException e) { /* ignore */ }
        }
        return enrollments;
    }
    
    @Override
    public boolean update(Enrollment enrollment) {
        Connection conn = null;
        PreparedStatement ps = null;
        try {
            conn = DatabaseConnector.getConnection();
            ps = conn.prepareStatement(UPDATE_SQL);
            ps.setInt(1, enrollment.getStudentID());
            ps.setInt(2, enrollment.getCourseID());
            ps.setString(3, enrollment.getReferenceID());
            ps.setString(4, enrollment.getDescription());
            ps.setTimestamp(5, new Timestamp(enrollment.getEnrollDate().getTime()));
            ps.setString(6, enrollment.getStatus());
            ps.setString(7, enrollment.getRemarks());
            ps.setInt(8, enrollment.getEnrollmentID());
            
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        } finally {
            try { if (ps != null) ps.close(); } catch (SQLException e) { /* ignore */ }
            try { if (conn != null) conn.close(); } catch (SQLException e) { /* ignore */ }
        }
    }
    /**
     * Checks if a specific student is already enrolled in a specific course.
     * Returns the status (e.g., "Active", "Pending") or null if not enrolled.
     */
    public String getEnrollmentStatus(int studentID, int courseID) {
        String sql = "SELECT Status FROM Enrollment WHERE StudentID = ? AND CourseID = ?";
        try (Connection conn = DatabaseConnector.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            
            ps.setInt(1, studentID);
            ps.setInt(2, courseID);
            
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return rs.getString("Status");
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null; // Not enrolled
    }
    public String getStudentCourseStatus(int studentID, int courseID) {
        String sql = "SELECT Status FROM Enrollment WHERE StudentID = ? AND CourseID = ?";
        try (Connection conn = DatabaseConnector.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            
            ps.setInt(1, studentID);
            ps.setInt(2, courseID);
            
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                return rs.getString("Status"); // Returns 'Active', 'Pending', etc.
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return "Not Enrolled"; 
    }

    @Override
    public boolean delete(int id) {
        Connection conn = null;
        PreparedStatement ps = null;
        try {
            conn = DatabaseConnector.getConnection();
            ps = conn.prepareStatement(DELETE_SQL);
            ps.setInt(1, id);
            
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        } finally {
            try { if (ps != null) ps.close(); } catch (SQLException e) { /* ignore */ }
            try { if (conn != null) conn.close(); } catch (SQLException e) { /* ignore */ }
        }
    }
}